name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add host key
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key -v ubuntu@$EC2_HOST 'echo "SSH Connection Successful"'

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          # Debug: mostrar diretório atual no EC2
          ssh -i ~/.ssh/deploy_key ubuntu@$EC2_HOST 'pwd'

          # Tentar criar o arquivo .env com debug
          echo "$PRODUCTION_ENV" | ssh -i ~/.ssh/deploy_key ubuntu@$EC2_HOST 'cat > /var/www/app/zeloclub-api/.env || echo "Failed to create .env file: $?"'

          # Resto do deploy
          ssh -i ~/.ssh/deploy_key ubuntu@$EC2_HOST '
            cd /var/www/app/zeloclub-api &&
            git pull origin main &&
            npm ci &&
            npx prisma generate &&
            npx prisma migrate deploy &&
            npm run build &&
            pm2 stop all &&
            pm2 delete all &&
            pm2 start dist/index.js --name "zeloclub-api" &&
            pm2 save
          '
