name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build application
        run: npm run build

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add host key
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@$EC2_HOST '
            cd /var/www/app/zeloclub-api &&
            echo "PORT=3000" > .env &&
            echo "NODE_ENV=production" >> .env &&
            echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> .env &&
            echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env &&
            echo "SENDGRID_API_KEY=\"${{ secrets.SENDGRID_API_KEY }}\"" >> .env &&
            echo "AWS_BUCKET_NAME=\"${{ secrets.AWS_BUCKET_NAME }}\"" >> .env &&
            echo "AWS_REGION=\"${{ secrets.AWS_REGION }}\"" >> .env &&
            echo "AWS_ACCESS_KEY_ID=\"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> .env &&
            echo "AWS_SECRET_ACCESS_KEY=\"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> .env &&
            echo "S3_BUCKET_NAME=\"${{ secrets.S3_BUCKET_NAME }}\"" >> .env &&
            echo "AUTH0_BASE_URL=\"${{ secrets.AUTH0_BASE_URL }}\"" >> .env &&
            echo "AUTH0_ISSUER_BASE_URL=\"${{ secrets.AUTH0_ISSUER_BASE_URL }}\"" >> .env &&
            echo "AUTH0_CLIENT_ID=\"${{ secrets.AUTH0_CLIENT_ID }}\"" >> .env &&
            echo "AUTH0_CLIENT_SECRET=\"${{ secrets.AUTH0_CLIENT_SECRET }}\"" >> .env &&
            echo "AUTH0_AUDIENCE=\"${{ secrets.AUTH0_AUDIENCE }}\"" >> .env &&
            echo "AUTH0_SECRET=\"${{ secrets.AUTH0_SECRET }}\"" >> .env &&
            git pull origin main &&
            npm ci &&
            npx prisma generate &&
            npx prisma migrate deploy &&
            npm run build &&
            pm2 stop all &&
            pm2 delete all &&
            pm2 start dist/index.js --name "zeloclub-api" &&
            pm2 save
          '
